version: '3.4'

volumes:
  dbdata:

services:
  webserver:
    container_name: webserver
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - ./www:/var/www/html:Z
    ports:
      - 8000:80

  database:
    container_name: database
    image: docker.io/library/mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Y@d1r054d1
      MYSQL_DATABASE: laradock
      MYSQL_USER: yadi
      MYSQL_PASSWORD: Y@d1r054d1
    ports:
      - 9906:3306
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: docker.io/phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    restart: always
    environment:
      PMA_HOST: database
    depends_on:
      - database